package opencode

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/actlane/actlane/packages/cli/internal/pack"
)

const generatorVersion = "actlane-go-opencode-0.1.0-alpha.1"

type Options struct {
	Target         string
	OutDir         string
	Check          bool
	FrozenLockfile bool
}

type Result struct {
	Files map[string][]byte
}

type policyBundle struct {
	Pack         string         `json:"pack"`
	Version      string         `json:"version"`
	Target       string         `json:"target"`
	Capabilities []string       `json:"capabilities"`
	Decisions    []string       `json:"decisions"`
	Rules        map[string]any `json:"rules"`
}

type lockfile struct {
	LockfileVersion int                   `json:"lockfileVersion"`
	Pack            string                `json:"pack"`
	Version         string                `json:"version"`
	Target          string                `json:"target"`
	Generator       string                `json:"generator"`
	SourceDigests   map[string]string     `json:"sourceDigests"`
	GeneratedFiles  []generatedFileRecord `json:"generatedFiles"`
	Metadata        map[string]string     `json:"metadata"`
}

type generatedFileRecord struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

func Generate(loaded *pack.LoadedPack, opts Options) (*Result, error) {
	if opts.Target != "opencode" {
		return nil, fmt.Errorf("unsupported target %q; supported target: opencode", opts.Target)
	}
	if opts.OutDir == "" {
		opts.OutDir = filepath.Join(loaded.Root, "generated")
	}

	files, err := render(loaded)
	if err != nil {
		return nil, err
	}
	files["actlane.lock"] = mustJSON(buildLockfile(loaded, files))

	result := &Result{Files: files}
	if opts.Check || opts.FrozenLockfile {
		if err := compareExisting(opts.OutDir, files, opts.FrozenLockfile); err != nil {
			return nil, err
		}
		return result, nil
	}
	if err := writeFiles(opts.OutDir, files); err != nil {
		return nil, err
	}
	return result, nil
}

func render(loaded *pack.LoadedPack) (map[string][]byte, error) {
	if len(loaded.Capabilities) != 1 {
		return nil, fmt.Errorf("OpenCode MVP expects exactly one capability, got %d", len(loaded.Capabilities))
	}
	capability := loaded.Capabilities[0]
	if capability.Metadata.Name != "create-github-draft-pr" {
		return nil, fmt.Errorf("OpenCode MVP capability must be create-github-draft-pr")
	}
	rules := collectRules(loaded.Policies)
	files := map[string][]byte{}
	files["opencode/opencode.snippet.jsonc"] = mustJSON(opencodeSnippet())
	files["opencode/commands/create-github-draft-pr.md"] = []byte(commandMarkdown(loaded.Manifest.Metadata.Name, capability, rules))
	files["opencode/agents/github-draft-pr.md"] = []byte(agentMarkdown(capability, rules))
	files["opencode/instructions/github-draft-pr.md"] = []byte(instructionsMarkdown(capability, rules))
	files["policies/policy-bundle.json"] = mustJSON(policyBundle{
		Pack:         loaded.Manifest.Metadata.Name,
		Version:      loaded.Manifest.Metadata.Version,
		Target:       "opencode",
		Capabilities: []string{capability.Metadata.Name},
		Decisions:    []string{"allow", "deny", "mutate", "requires-approval"},
		Rules:        rules,
	})
	return files, nil
}

func opencodeSnippet() map[string]any {
	return map[string]any{
		"$schema": "https://opencode.ai/config.json",
		"instructions": []string{
			".actlane/generated/opencode/instructions/github-draft-pr.md",
		},
		"permission": map[string]string{
			"bash": "ask",
			"edit": "ask",
		},
		"agent": map[string]any{
			"github-draft-pr": map[string]any{
				"description": "Prepare safe GitHub draft pull requests from reviewed changes.",
				"prompt":      "Follow the generated github-draft-pr instructions and create only draft pull requests after explicit confirmation.",
				"tools": map[string]bool{
					"edit":  true,
					"write": true,
				},
			},
		},
		"command": map[string]any{
			"create-github-draft-pr": map[string]string{
				"description": "Prepare a safe GitHub draft PR",
				"agent":       "github-draft-pr",
				"template":    "Prepare a GitHub draft PR using the generated github-draft-pr capability contract. Refuse secrets, force draft=true, require confirmation before mutation, and report policy decision.",
			},
		},
	}
}

func commandMarkdown(packName string, capability pack.Capability, rules map[string]any) string {
	return fmt.Sprintf(`# create-github-draft-pr

Generated by Actlane from pack %s and capability %s.

Use this OpenCode command when changes have already been reviewed and the user asks to prepare a GitHub draft pull request.

## Required Flow

1. Inspect git status and changed files.
2. Refuse secret, credential, token, and private-key paths.
3. Refuse unreviewed or excessive file sets.
4. Run the configured test command when present.
5. Ask for explicit confirmation before creating a branch, commit, or pull request.
6. Create a branch with prefix %s.
7. Commit reviewed files only.
8. Create the GitHub pull request with draft=true.
9. Return PR URL, branch, files, test status, and policy decision.

## Inputs

%s

## Reporting

- Include changed files.
- Include policy decision.
- Include draft PR URL when created.
`, packName, capability.Metadata.Name, stringValue(rules["branchPrefix"]), fieldList(capability.Spec.Inputs))
}

func agentMarkdown(capability pack.Capability, rules map[string]any) string {
	return fmt.Sprintf(`# github-draft-pr

%s

## Safety Contract

- Create only GitHub draft pull requests.
- Require explicit user confirmation before mutation.
- Force branch prefix %s.
- Deny secret-like paths: %s.
- Never include files outside the reviewed file list.
- Prefer running configured project tests before creating the PR.
`, capability.Spec.WhenToUse, stringValue(rules["branchPrefix"]), strings.Join(stringSlice(rules["forbiddenPaths"]), ", "))
}

func instructionsMarkdown(capability pack.Capability, rules map[string]any) string {
	return fmt.Sprintf(`# GitHub Draft PR Instructions

Capability: %s

Before mutating repository or GitHub state, check the Actlane policy bundle and ask for explicit confirmation.

Defaults:

- draft: true
- branch prefix: %s
- maximum files: %v
- maximum diff bytes: %v

Return a concise summary with policy decision, changed files, final branch, and draft PR URL.
`, capability.Metadata.Name, stringValue(rules["branchPrefix"]), rules["maxFiles"], rules["maxDiffBytes"])
}

func fieldList(fields map[string]pack.Field) string {
	names := make([]string, 0, len(fields))
	for name := range fields {
		names = append(names, name)
	}
	sort.Strings(names)
	var b strings.Builder
	for _, name := range names {
		required := "optional"
		if fields[name].Required {
			required = "required"
		}
		fmt.Fprintf(&b, "- `%s` (%s, %s)\n", name, fields[name].Type, required)
	}
	return strings.TrimRight(b.String(), "\n")
}

func collectRules(policies []pack.Policy) map[string]any {
	forbidden := []string{}
	rules := map[string]any{
		"branchPrefix":   "actlane/",
		"forceDraft":     true,
		"maxFiles":       20,
		"maxDiffBytes":   120000,
		"forbiddenPaths": forbidden,
	}
	for _, policy := range policies {
		for _, deny := range policy.Spec.Deny {
			if deny.MaxFiles != 0 {
				rules["maxFiles"] = deny.MaxFiles
			}
			if deny.MaxDiffBytes != 0 {
				rules["maxDiffBytes"] = deny.MaxDiffBytes
			}
			forbidden = append(forbidden, deny.Paths...)
		}
		for _, mutate := range policy.Spec.Mutate {
			if mutate.Field == "branch" && mutate.EnsurePrefix != "" {
				rules["branchPrefix"] = mutate.EnsurePrefix
			}
			if mutate.Field == "draft" {
				if value, ok := mutate.Value.(bool); ok {
					rules["forceDraft"] = value
				}
			}
		}
	}
	sort.Strings(forbidden)
	rules["forbiddenPaths"] = forbidden
	return rules
}

func buildLockfile(loaded *pack.LoadedPack, files map[string][]byte) lockfile {
	sourceDigests := map[string]string{
		"actlane.yaml": digest(loaded.ManifestRaw),
	}
	for _, capability := range loaded.Capabilities {
		sourceDigests[relToRoot(loaded.Root, capability.Path)] = digest(capability.Raw)
	}
	for _, policy := range loaded.Policies {
		sourceDigests[relToRoot(loaded.Root, policy.Path)] = digest(policy.Raw)
	}

	paths := make([]string, 0, len(files))
	for path := range files {
		if path != "actlane.lock" {
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)
	records := make([]generatedFileRecord, 0, len(paths))
	for _, path := range paths {
		records = append(records, generatedFileRecord{
			Path:   path,
			SHA256: digest(files[path]),
		})
	}
	return lockfile{
		LockfileVersion: 1,
		Pack:            loaded.Manifest.Metadata.Name,
		Version:         loaded.Manifest.Metadata.Version,
		Target:          "opencode",
		Generator:       generatorVersion,
		SourceDigests:   sourceDigests,
		GeneratedFiles:  records,
		Metadata: map[string]string{
			"schema": "actlane.ru/v1alpha1",
		},
	}
}

func compareExisting(outDir string, files map[string][]byte, frozen bool) error {
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, rel := range paths {
		existing, err := os.ReadFile(filepath.Join(outDir, rel))
		if err != nil {
			if frozen && rel == "actlane.lock" {
				return fmt.Errorf("lockfile is missing or unreadable: %w", err)
			}
			return fmt.Errorf("generated output is stale: %s is missing", rel)
		}
		if !bytes.Equal(existing, files[rel]) {
			if frozen && rel == "actlane.lock" {
				return fmt.Errorf("lockfile would change")
			}
			return fmt.Errorf("generated output is stale: %s differs", rel)
		}
	}
	return nil
}

func writeFiles(outDir string, files map[string][]byte) error {
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, rel := range paths {
		if err := writeAtomic(filepath.Join(outDir, rel), files[rel]); err != nil {
			return err
		}
	}
	return nil
}

func writeAtomic(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func mustJSON(value any) []byte {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		panic(err)
	}
	return append(data, '\n')
}

func digest(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

func relToRoot(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return filepath.ToSlash(rel)
}

func stringValue(value any) string {
	if s, ok := value.(string); ok {
		return s
	}
	return ""
}

func stringSlice(value any) []string {
	items, ok := value.([]string)
	if !ok {
		return nil
	}
	return items
}
